### ISSUE TITLE
Clean code

### ISSUE THREAD

**Issue by nakidai** [Murchik0v/murchikov-site#1]
There are so many references to a certain AndcoolSystems, I think that they all are mistakes and they are unneeded, so you can just delete them because this is your project, isn't it?

**Comment by nakidai** [comment]
Agreed.

**Comment by Andcool-Systems** [comment]
Yes, I think so too. Some AndcoolSystems is not worthy to be mentioned in such a wonderful project

**Comment by gimura2022** [comment]
I agree, why should some AndcoolSystems be mentioned in the code, what does he have to do with it?

**Comment by nakidai** [comment]
> Andcool Systems doesn't even seem to be able to do that. It's too wonderful a project for him.

I think he hacked the source code of this repo and added his nickname ot the code

**Comment by Jagorrim** [comment]
who does want to play some chess

**Comment by messengernew** [comment]
> > Andcool Systems doesn't even seem to be able to do that. It's too wonderful a project for him.
> 
> I think he hacked the source code of this repo and added his nickname to the code

Andcool clearly stole the first version of this perfect and wonderful site and posted it before this person. how dare he((

**Comment by messengernew** [comment]
> Exactly, he could never make such a site.

true

**Comment by nakidai** [comment]
I hope this issue will be closed as completed with removing all references to such a bad person like AndcoolSystems, he really does bad things and we know it.

**Comment by MrCheatEugene** [comment]
i think that's true

**Comment by nakidai** [comment]
> i think that's true

This IS true, you know?

**Comment by imyoric** [comment]
I agree with everything that was written here. Endkul is truly a bad person and should be removed from this wonderful repository forever.

**Comment by s3nkwr** [comment]
I think Murchikov should finally make textures for Tablist, and not steal them from others.

**Comment by MrCheatEugene** [comment]
Remove andcool uncool code and delete this repository from existence

**Comment by nakidai** [comment]
> I think Murchikov should finally make textures for Tablist, and not steal them from others.

Did you know that @Murchik0v is the original author of the site, and @Andcool-Systems stole it without any mentioning of the Murchik0v?

**Comment by gimura2022** [comment]
> > I think Murchikov should finally make textures for Tablist, and not steal them from others.
> 
> Did you know that @Murchik0v is the original author of the site, and @Andcool-Systems stole it without any mentioning of the Murchik0v?

yes it is true

**Comment by nakidai** [comment]
Guys read the first messages, andcool if THIEF

**Comment by Shaehl** [comment]
your actions will be prohibited, not cool @Andcool-Systems, not cool

**Comment by ModEratorTA** [comment]
site pisdatiy a andcool gondon

**Comment by Shaehl** [comment]
> a andcool gondon
💯 gandon

**Comment by satananp228** [comment]
@Andcool-Systems what a shame? Why did you decide to brazenly steal such a beautiful site? I am completely frustrated. I did not expect such a vile act from you. Trash 😑. @Murchik0v do you agree with me?

**Comment by messengernew** [comment]
> @Andcool-Systems what a shame? Why did you decide to brazenly steal such a beautiful site? I am completely frustrated. I did not expect such a vile act from you. Trash 😑. @Murchik0v do you agree with me?

I agree with you.

**Comment by Murchik0v** [comment]
Wtf

**Comment by Murchik0v** [comment]
no comments
